### ISSUE TITLE
column separator in exported file (... messed up for "support gems")

### ISSUE THREAD

**Issue by ujiko** [benjaminjackman/looty#12]
GGG has changed the names on support gems and added comma(s) in the description. This corrupts the exported file.
Example:  _Chaos, Support,Added Chaos Damage Support_ (in GemKeyWords/TypeLine) 

Is it possible to delimit text strings w quotes (or maybe let the user choose a column separator in Looty)?

**Comment by benjaminjackman** [comment]
should be fixed (with quotes for items that have commas) in v65

**Comment by ujiko** [comment]
Great! Thanks! mhoty!!!
/ujiko
