### ISSUE TITLE
Add pull prices from poe.ninja button to the wealth tab

### ISSUE THREAD

**Issue by thebeast792** [benjaminjackman/looty#16]
Can you add an option in the "Wealthy" section to use poe.ninja to calculate the chaos ratios so that the user doesn't need to enter them every time?

**Comment by benjaminjackman** [comment]
Adding a pull from poe.ninja button would be nice.

And at the very least it should definitely be saving the values so that you don't have to re-enter them every single time as that sounds really awful.

**Comment by benjaminjackman** [comment]
Just noticed this is actually a duplicate of #13
