### ISSUE TITLE
Looty not getting Data From GGG

### ISSUE THREAD

**Issue by Groosum** [benjaminjackman/looty#25]
Please could you look at this I use it so much. I am disabled so it takes a long time for me to find gear looking through tabs.

I need this.

**Comment by kameryl** [comment]
Same issue here, its load the stash layout, but no items at all.

**Comment by zornaq** [comment]
I also need this tool back. It's perfect with loads of tabs.

Information for dev: GGG changed some things with API fetching. Problem probably is there.

**Comment by radeor** [comment]
Hey guys I can't replicate the issue it seems to be working fine for me. If anyone can post some logs from the developer tools to this ticket i'll take a look.

Things I'd suggest:
1. Make sure you are logged in at pathofexile.com
2. Under refresh/tabs try doing Clear and Reload everything for these league from this server
3. Un/install reinstall looty.

**Comment by PetePete1984** [comment]
I've also reinstalled and updated my dev environment again, but the errors I'm getting are weird.
The console prints out "Failure in async execution: TypeError: Cannot read property 'length' of undefined" on some tabs when I force refresh single tabs, but not on all of them.

**Comment by radeor** [comment]
that sounds weird, dang i wish i could replicate it, maybe they
changed up some fields in some of the messages or something

**Comment by PetePete1984** [comment]
After upgrading scala.js and sbt, I got it to print a proper stack trace. Apparently it's crashing in this function: https://github.com/benjaminjackman/looty/blob/master/looty/src/main/scala/looty/poeapi/PoeTypes.scala#L70 on the socketedItems.toList bit - apparently socketedItems is now an optional property?
I'll be honest - I don't know how to fix this, because the whole functional nature of Scala entirely eludes me. I feel like I can't understand what I'm reading in this bit, and *all it needs is a null check*.

**Comment by radeor** [comment]
wow nice catch, that's helpful, they must have added some new items or something. i'll change that to be optional and hopefully that will fix the issue

**Comment by radeor** [comment]
yeah with options in scala it takes some getting used to, in an imperative language it definitely would be a null check type of a thing, in the functional languages whether something is null or not is preferably encoded into a container with 1 or 0 items (called an option in scala).

**Comment by PetePete1984** [comment]
`object ItemContainer {
    implicit class ItemContainerExtensions(val ic: ItemContainer) extends AnyVal {
      def allItems(character: Option[String]): List[AnyItem] = {
        ic.items.toList.flatMap { item =>
        // socketedItems is now optional
        // if it's not empty..
          if (item.socketedItems.nonEmpty) {
            // get its contents, transform them to a list
            // return all socketed items in a list with their parent
            (item :: item.socketedItems.get.toList.map { i =>
              i.inItem = item
              i
            }) map { i =>
              character.foreach(c => i.character = c)
              i.locationId = i.getLocationId
              i
            }
          } else {
            // when there are no socketed items, just return a list with the item
            character.foreach(c => item.character = c)
            item.locationId = item.getLocationId
            List(item)
          }
        }
      }
    }
  }`

This fixes it, together with `val socketedItems: Optional[js.Array[AnyItem]] = js.native` instead of https://github.com/benjaminjackman/looty/blob/master/looty/src/main/scala/looty/poeapi/PoeTypes.scala#L368

**Comment by radeor** [comment]
do you want to do a PR ? i'll merge it and deploy it next time I am able

**Comment by PetePete1984** [comment]
I'm unsure if I should include the sbt and scala.js upgrades, technically I only needed those to find the problem. I'll test without them, make a clean branch with only the relevant changes and submit a PR, yeah.

**Comment by radeor** [comment]
maybe make a second pr with that after? i'm not sure I want to change the
sbt / scalajs versions but if you need it updated to build and it doesn't
break anything on my side i can merge them separately

**Comment by PetePete1984** [comment]
PR is up at https://github.com/benjaminjackman/looty/pull/26, didn't need the sbt and scala updates yet. They *might* be useful in the future if we run into nondescript crashes again.

**Comment by Groosum** [comment]
Just like to Thank everyone an especially you "PetePete1984" for the work you doing.

Could the New belts with sockets in them be causing it at all an sorry if seems silly comment but i not really that tech smart as far as coding goes I'm an end user of great stuff like this.
.
