### ISSUE TITLE
Possible to search for empty affix/preffix 

### ISSUE THREAD

**Issue by Traf27** [benjaminjackman/looty#29]
Would it be possible to add functionality to search for empty affixes/preffix/suffixes of an item ?
Sometimes I'd like to find good item which could be bench crafted or ex slammed.

**Comment by kevindevm** [comment]
i think the only way is searching on official trade for that item under your account

**Comment by Traf27** [comment]
I found solution, didn't know about filter "emc" - the number of explicit mods on an item - if its less then 6 then probably you can add affix on a bench. Since it can't differ between two-stats affixes like increased phys dmg % and + to accuracy rating.

Thanks
