### ISSUE TITLE
lireg Stat does not seem to be working.

### ISSUE THREAD

**Issue by synicasm** [benjaminjackman/looty#41]
Life Regen can be represented 2 ways

Regenerate %  of Life per Second 
Regenerate X life per second.

Neither appear to be showing up under this category.

![Regen1](https://user-images.githubusercontent.com/19449647/74613846-3a986000-50c7-11ea-9f50-8d1daf4e228f.png)
![Regen2](https://user-images.githubusercontent.com/19449647/74613847-3b30f680-50c7-11ea-9d25-6bdc6a15a4de.png)

**Comment by AnnanFay** [comment]
I noticed this today so just posting to confirm it. JSON Example: 
```
{
        [...]
        "name": "Araku Tiki",
        "typeLine": "Coral Amulet",
        "identified": true,
        "ilvl": 9,
        "implicitMods": [
            "Regenerate 2.2 Life per second"
        ],
        "explicitMods": [
            "+100 to Evasion Rating while on Low Life", 
            "+32 to maximum Life", 
            "+27% to Fire Resistance", 
            "Regenerate 1% of Life per second while on Low Life"
        ],
        [...]
    }
```

I don't know scala so having trouble figuring out where in the code even handles this. I think [this is the current code](https://github.com/benjaminjackman/looty/blob/b8b1c6fb370db9f94c56b9da6e26af521f719b64/looty/src/main/scala/looty/mods/ModsCsvParser.scala#L201). It's using the parser:

```scala
P.simple1("", s"Life Regenerated per second")(_.other.lifeRegeneratedPerSecond)```

This compiles to the expression: `^([.+-\\d]+)%* Life Regenerated per second$`

I think the fix needed is to replace the above with: ```scala
P.simple1("Regenerate", s"Life per second")(_.other.lifeRegeneratedPerSecond)
```

For the original code just adds together all life regeneration mods but having them separate seems like a good idea. Something like: ```scala
    addMod("% Life regeneration",
      "Percent Life Regeneration Rate Per Second",
      P.simple1("Regenerate", s"of Life per second.*")(_.other.lifePercentRegeneratedPerSecond))
```

Then `lifePercentRegeneratedPerSecond` would need to be added to the other files.

**Comment by Traf27** [comment]
I think I got it right.
@AnnanFay  you are on the right track.
As far as I was able to deduce, adding parsing for affix is done in 3 files:
1. [ComputedItem.scala](looty/src/main/scala/looty/model/ComputedItem.scala) where you set how it's referenced in next 2 files, also variable with which JSON data will be mached (im not sure how to call it, see for yourself)
2. [ComputedItemProps.scala ](looty/src/main/scala/looty/model/ComputedItemProps.scala)where you choose name for button/column, and description (and if you wonder the ?= are for setting default columns on, so  !?= sets them off) 
3. and ofc [AffixesParser.scala](looty/src/main/scala/looty/model/parsers/AffixesParser.scala) where you make regex for  affix
