### ISSUE TITLE
Attributes treated inconsistently

### ISSUE THREAD

**Issue by AnnanFay** [benjaminjackman/looty#43]
The way the program treats the three primary stats is weird. Here is an example:

![image](https://user-images.githubusercontent.com/766048/77243115-25e74480-6bfe-11ea-93a3-a86e193a41c2.png)

Looty lists this as giving +15% Evasion (`IncreasedEvasion`). Compare that to this:

![image](https://user-images.githubusercontent.com/766048/77243142-8080a080-6bfe-11ea-9db1-4645cef9fb33.png)

Which shows up as 6.6% increased maximum energy shield (`IncreasedMaxEnergyShield`).

The second item integrates the effect of Intelligence into the global ES modifier (2% + 4.6%) while the first item does not integrate Dexterity. So, what happens when you have a piece of equipment with a local % modifier *and* an Intelligence bonus?

![image](https://user-images.githubusercontent.com/766048/77243243-bd996280-6bff-11ea-9311-e40479953c7f.png)

This item Looty will show as having: 24% increased evasion and 7% increased ES.

So increased ES will *always* be global increased ES including intelligence.
Increased Evasion will either be local increase, or it will be global increase ignoring dexterity.

I'm not sure what the best way to fix this is but it would be nice if there was a consistent treatment of local and global modifiers. There's currently no way of retrieving a local ES modifier, or seeing the full global evasion modifier on an item.

**Comment by Traf27** [comment]
I've fixed this issue in my local repo - which I hope I'll put into PR soon. I'd like to make it before next league.

I have added:
- local Energy Shield %
- local Armour %
- local Evasion Rating %
Changed:
- Evasion Rating to global, and included dexterity, more so I have converted each item with dex, to show global Evasion Rating
- #% increased Armour to global one

**Comment by benjaminjackman** [comment]
ok sounds good to me, thanks, when is the next league?

**Comment by Traf27** [comment]
15th friday ;)
