### ISSUE TITLE
Chance to Dodge Attacks / Spells should be added

### ISSUE THREAD

**Issue by AnnanFay** [benjaminjackman/looty#44]
Change to dodge is both an implicit and explicit modifier for shields. This stat is important in builds which stack dodge and should be added to looty.

Example rare item with implicit and explicit mods:

![image](https://user-images.githubusercontent.com/766048/79627413-db3ee680-812f-11ea-8925-8a444f4a797f.png)

```Rarity: Rare
Corpse Mark
Compound Spiked Shield
--------
Chance to Block: 25%
Evasion Rating: 122
Energy Shield: 24
--------
Requirements:
Level: 45
Dex: 58
Int: 58
--------
Sockets: G-G-G 
--------
Item Level: 46
--------
2% chance to Dodge Spell Hits (implicit)
--------
+32 to Intelligence
+45 to maximum Life
+26% to Lightning Resistance
2% chance to Dodge Attack Hits
```

**Comment by AnnanFay** [comment]
Spell block also appears to be missing:
![image](https://user-images.githubusercontent.com/766048/79628023-2ad3e100-8135-11ea-9cc7-db1e2a5cc83d.png)

```
Rarity: Rare
Miracle Song
Fossilised Spirit Shield
--------
Chance to Block: 24% (augmented)
Energy Shield: 64 (augmented)
--------
Requirements:
Level: 59
Int: 141
--------
Sockets: B-B-B 
--------
Item Level: 71
--------
19% increased Spell Damage (implicit)
--------
11% Chance to Block Spell Damage
+17 to maximum Energy Shield
+33 to maximum Life
Regenerate 11.9 Life per second
+2% Chance to Block
```

**Comment by Traf27** [comment]
Thanks!
I'll look into it. 
And will try to push update to pull req.

**Comment by Traf27** [comment]
Does **chance to block spell damage** stack with **chance to block** ?

**Comment by AnnanFay** [comment]
@Traf27 They never stack. Chance to Block is just short-form for blocking attacks.
