### ISSUE TITLE
Darkshrine tab doesnt work

### ISSUE THREAD

**Issue by carlosesilva** [benjaminjackman/looty#9]
Hi,

Thank you so much for the amazing work.
Just wanted to let you know that the DarkShrine tab doesn't work.
You can click on it but it does not open anything, the only thing it does is modify the url path, but thats it.

**Comment by benjaminjackman** [comment]
i'm going to close this since the darkshrine league was so long ago, sorry for not responding in a timely fashion, I have since made changes so that Looty should automatically detect and add leagues as they appear.

Sorry again for the extreme lag in response
